name: Generate and propose changes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"

jobs:
  generate-and-propose-changes:
    permissions:
      contents: write
      pull-requests: write
    name: Generate and propose changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo run -- generate

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Periodic update"
          title: "Periodic update"
          body: |
            Produced by [`.github/workflows/update.yml`](https://github.com/edigaryev/awesome-system-calls/blob/main/.github/workflows/update.yml).
